name: Deploy AWS Glue Job

on:
  push:
    branches:
      - main  # Change branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run specific test functions related to AWS glue
        run: |
          pytest tests/test_main.py::test_s3_buckets
          pytest tests/test_main.py::test_glue_job_exists_and_is_runnable

      - name: Upload Glue Script to S3
        run: |
          aws s3 cp glue_jobs/historical_data_transformation.py s3://aws-glue-assets-350681797086-eu-north-1/scripts/
          aws s3 cp glue_jobs/intra_day_transformation.py s3://aws-glue-assets-350681797086-eu-north-1/scripts/
        